---
name: DateTime-Format-HTTP
version: 0.38
author:
  - 'Dave Rolsky <autarch@urth.org>'
abstract: Date conversion routines
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0.17
  HTTP::Date: 1.44
  Test::More: 0.47
provides:
  DateTime::Format::HTTP:
    file: lib/DateTime/Format/HTTP.pm
    version: 0.38
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
