--- #YAML:1.0
name: DateTime-Format-HTTP
version: 0.36
license: perl
distribution_type: module
requires:
  DateTime: 0.17
  HTTP::Date: 1.44
  Test::More: 0.47
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::HTTP:
    file: lib/DateTime/Format/HTTP.pm
    version: 0.36
generated_by: Module::Build version 0.20
