---
abstract: Date conversion routines
author:
  - 'Christiaan Kras <ckras@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-HTTP
provides:
  DateTime::Format::HTTP:
    file: lib/DateTime/Format/HTTP.pm
    version: 0.42
requires:
  DateTime: 0.17
  HTTP::Date: 1.44
  Test::More: 0.47
resources:
  license: http://dev.perl.org/licenses/
version: 0.42
